from enum import StrEnum

class CategoryEnum(StrEnum):
    SEWERAGE_DRAINAGE = "SEWERAGE_DRAINAGE"
    WASTE_SANITATION = "WASTE_SANITATION"
    WATER_SUPPLY = "WATER_SUPPLY"
    ELECTRICITY = "ELECTRICITY"
    STREET_LIGHTING = "STREET_LIGHTING"
    ROAD_DAMAGE = "ROAD_DAMAGE"
    GAS_UTILITIES = "GAS_UTILITIES"
    PARKS_HORTICULTURE = "PARKS_HORTICULTURE"
    STRAY_ANIMALS_SAFETY = "STRAY_ANIMALS_SAFETY"
    OTHER = "OTHER"

class DepartmentEnum(StrEnum):
    WATER_SANITATION = "WATER_SANITATION"
    WATER_SUPPLY = "WATER_SUPPLY"
    WASTE_MANAGEMENT = "WASTE_MANAGEMENT"
    ROAD_MAINTENANCE = "ROAD_MAINTENANCE"
    PUBLIC_LIGHTING = "PUBLIC_LIGHTING"
    ELECTRICITY_UTILITY = "ELECTRICITY_UTILITY"
    GAS_UTILITY = "GAS_UTILITY"
    PARKS_HORTICULTURE = "PARKS_HORTICULTURE"
    ANIMAL_CONTROL = "ANIMAL_CONTROL"
    MANUAL_REVIEW = "MANUAL_REVIEW"

class PriorityEnum(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class IncidentStatusEnum(StrEnum):
    RECEIVED = "RECEIVED"
    VERIFIED = "VERIFIED"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED = "RESOLVED"
    REOPENED = "REOPENED"
    REJECTED = "REJECTED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
